---

- name: APT -- Update cache & packages
  apt:
    update_cache: yes
    upgrade: full

- name: APT -- Install base packages
  apt: state=latest pkg={{ item }}
  with_items:
    - vim
    - wget
    - htop
    - screen
    - ufw
    - apache2

- name: APT -- Install devel packages
  apt: state=latest pkg={{ item }}
  with_items:
    - git
    - build-essential
    - cmake
    - libeigen3-dev
    - libboost-all-dev
    - libyaml-cpp-dev
    - zlib1g-dev
