---
- hosts: localhost
  connection: local

  tasks:
    - name: launch
      ec2:
        key_name: "{{ key_name }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
      register: ec2
    - name: wait for SSH to come up
        wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
        with_items: ec2.instances

